//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(UsersMetaData))]
    public partial class Users
    {

        public int UserID { get; set; }

        [Display(Name = "نقش کاربر")]
        public int RoleID { get; set; }

        [Display(Name = "نام کاربری")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public string UserName { get; set; }


        [Display(Name = "ایمیل")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        [EmailAddress(ErrorMessage = "ایمیل وارد شده معتبر نمی باشد")]
        public string Email { get; set; }



        [Display(Name = "کلمه ی عبور")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public string Password { get; set; }



        [Display(Name = "کد فعالسازی")]
        public string ActiveCode { get; set; }


        [Display(Name = "وضعیت")]
        public bool IsActive { get; set; }



        [Display(Name = "تاریخ ثبت نام")]
        public System.DateTime RegisterDate { get; set; }

        public virtual Roles Roles { get; set; }
    }
}
